volumes:
  postgres:

services:
  postgres:
    image: postgres:14.13-alpine3.20
    container_name: osn-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:cached

  osn-api:
    build:
      context: .
      dockerfile: OSN/Dockerfile
    ports:
      - "5069:5069"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "5069"
      CUSTOMCONNSTR_DefaultConnection: "Host=postgres;Port=5432;Database=default;Username=user;Password=password"
      Jwt__Key: R11B+Pm+sjmNR6wj7vvZlhe3nBi/bFeCzGydkEUOQK8=
      Jwt__Issuer: OSN
      Jwt__Audience: OSNAudience
    working_dir: /app